controller_names:
  - left_franka_arm
  - left_franka_gripper
  - right_franka_arm
  - right_franka_gripper

left_franka_arm:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - left_fr3_joint1
    - left_fr3_joint2
    - left_fr3_joint3
    - left_fr3_joint4
    - left_fr3_joint5
    - left_fr3_joint6
    - left_fr3_joint7

left_franka_gripper:
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - left_fr3_finger_joint1
      - left_fr3_finger_joint2

right_franka_arm:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - right_fr3_joint1
    - right_fr3_joint2
    - right_fr3_joint3
    - right_fr3_joint4
    - right_fr3_joint5
    - right_fr3_joint6
    - right_fr3_joint7

right_franka_gripper:
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - right_fr3_finger_joint1
      - right_fr3_finger_joint2